config/routes.rb
Rails.application.routes.draw do

  root 'login#index'
  
  resources :users
  post 'login' => 'login#login', :as => 'login'
  get 'logout' => 'login#logout', :as => 'logout'
  get 'auth_token' => 'auth_token#index', :as => 'auth_token'
  get 'gen_token' => 'auth_token#gen_token', :as => 'gen_token'
  get 'delete_token' => 'auth_token#delete_token', :as => 'delete_token'

  resources :tags  do 
    resources :events
  end
  resources :events do
    resources :tags
    resources :creators
    resources :positions
  end
  resources :creators do
    resources :events
  end
  resources :positions do
    resources :events    
  end

end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    has_one :token
    
    #validation for name
    validates :name, :presence => {:message => 'Du måste ange ett namn'}
    
    #validation for password
    validates :password, :presence => {:message => 'Du måste ange ett lösenord'}    
    validates :password_confirmation, :presence => {:message => 'Upprepa lösenordet'}
    
    #validation for email
    validates :email, 
    :presence => {:message => 'Du måste ange en epost'}, 
    :uniqueness => {:message => 'Eposten är redan registrerad'}
    
    validates_format_of :email, :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/,
    :presence => {:message => 'Felaktigt format på eposten'}    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:index]

    def index
        if !current_user.nil?
            if !is_admin
                redirect_to auth_token_path                
            end
            @users = User.all
        end
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        messages = Array.new

        if @user.save
            t = Token.new
            t.user_id = @user.id
            t.save
            redirect_to auth_token_path
        else
            render :action => 'new'
        end             
    end
    
	private
	
	def user_params
		params.require(:user).permit(:name, 
	                                 :email, 
	                                 :password, 
	                                 :password_confirmation);
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div id="logout" >
	<%= link_to "Logga ut", logout_path, class: "btn btn-primary" %>
</div>
<div id="users-list" class="list-group">
	<ul>
		<% if @users.size > 1 %>
			<% @users.each do |user| %>
				<li class="list-group-item">
					<ul>
						<li class="list-group-item">Namn: <%= user.name %></li>
						<li class="list-group-item">Epost: <%= user.email %></li>
						<% if !user.token.nil? %>
							<% if user.token.token.nil? %>
								<li class="list-group-item">Api Nyckel: Ingen nyckel</li>
							<% else %>
								<li class="list-group-item">
									Api Nyckel: <%= user.token.token %>
									<%= link_to "Ta bort nyckel", delete_token_path(:user_id => user.id) %>
								</li>
							<% end %>					
						<% end %>
					</ul>
				</li>
			<% end %>
		<% else %>
			Inga användare registrerade ännu
		<% end %>
	</ul>
</div>

app/views/users/new.html.erb
<div class="well bs-component">
	<div id="register-form" class="form-horizontal">
		<div class="flash-notice">
        	<% if @user.errors.any? %>
				<div id="error_messages">
					<ul>
						<% @user.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
    	</div>
	    <%= form_for @user do |f| %>
	       Ange namn: <%= f.text_field :name %>
	       Ange epost: <%= f.text_field :email %>
	       Ange lösenord: <%= f.password_field :password %>
	       Upprepa lösenord: <%= f.password_field :password_confirmation %>
	       <%= f.submit "Registrera användare" %>
	    <% end %>
	</div>
</div>