config/routes.rb
Rails.application.routes.draw do

  root 'login#index'
  
  resources :users
  post 'login' => 'login#login', :as => 'login'
  get 'logout' => 'login#logout', :as => 'logout'
  get 'auth_token' => 'auth_token#index', :as => 'auth_token'
  get 'gen_token' => 'auth_token#gen_token', :as => 'gen_token'
  get 'delete_token' => 'auth_token#delete_token', :as => 'delete_token'

  resources :tags  do 
    resources :events
  end
  resources :events do
    resources :tags
    resources :creators
    resources :positions
  end
  resources :creators do
    resources :events
  end
  resources :positions do
    resources :events    
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    
    def login
        email = params[:email]
        password = params[:password]
        message = "";
        appUser = User.find_by_email(email)
        
        if appUser && appUser.authenticate(password)
            session[:userid] = appUser.id
            if is_admin
                redirect_to users_path
            else
                redirect_to auth_token_path
            end
        else
            if email == ""
                message = 'Du måste ange en epost'
            elsif password == ""
                message = 'Du måste ange ett lösenord'
            else
                message = "Fel epost och/eller lösenord"
            end
            redirect_to root_path, :notice => message #return user to the login page
        end
    end
    
    def logout
        session[:userid] = nil
        redirect_to root_path, :notice => 'Du har loggats ut'
    end
    
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/index.html.erb
<div class="well bs-component">
    <div id="log-in-form" class="form-horizontal">
        <div class="flash-notice">
            <p><%= flash[:notice] %></p>
        </div>
        <%= form_tag(login_path, method: "post") do %>
            <p>
                <%= label_tag(:email, "Epost:") %>
            </p>
            <p>
                <%= email_field_tag(:email) %>
            </p>
            <p>
                <%= label_tag(:password, "Lösenord") %>
            </p>
            <p>
                <%= password_field_tag(:password) %>
            </p>
            <p>
                <%= submit_tag "Logga in" %>
                <%= link_to "Registrera", new_user_path %>
            </p>
        <% end %>
    </div>
</div>